/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 clickbox001blend.gltf --transform 
Files: clickbox001blend.gltf [5.37KB] > clickbox001blend-transformed.glb [1.2KB] (78%)
*/

import { useEffect, useRef } from "react";
import { motion as threeMotion } from "framer-motion-3d";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import useChangeCube from "@/hooks/useChangeCube";
export function Clickbox(props) {
  const { nodes, materials } = useGLTF(
    "models/clickbox/clickbox001blend-transformed.glb",
  );
  const { rotationAngle, color, startRotation } = useChangeCube();
  const clickBox = useRef();

  useFrame(() => {
    if (Math.abs(clickBox.current.rotation.y - rotationAngle) > 0.001) {
      clickBox.current.rotation.y +=
        (rotationAngle - clickBox.current.rotation.y) * 0.05; // Smoothly rotate to the desired angle
    }
  });
  // useEffect(() => {
  //   startRotation(-1);
  // }, []);
  return (
    <>
      <group {...props} dispose={null} ref={clickBox}>
        <threeMotion.mesh
          name={props.name}
          whileHover={{ scale: 1.1 }}
          whileTap={{ scale: 0.9 }}
          geometry={nodes.Cube.geometry}
          material={materials.Material}
          metalness={0.5}
          roughness={0.5}
          envMapIntensity={4}
          toneMapped={false}
          fog={false}
        >
          <meshStandardMaterial emissive={color} color={color} />
        </threeMotion.mesh>
      </group>
    </>
  );
}

useGLTF.preload("models/clickbox/clickbox001blend-transformed.glb");
