export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const SET_TYPES = "SET_TYPES";
export const CHANGE_QUANTITY = "CHANGE_QUANTITY";
export const CHANGE_SHIPPING_COST = "CHANGE_SHIPPING_COST";
